language: node_js
node_js:
  - '4'
install: npm install
script:
  - ./node_modules/gulp/bin/gulp.js
  - npm test
before_install:
  - 'sh -e /etc/init.d/xvfb start'
before_script:
  - 'export DISPLAY=:99.0'
notifications:
  irc:
    channels:
      - "irc.mozilla.org#wadi"
    skip_join: true
